name: ci

on:
  pull_request:
    branchs: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          nonde-version: 18

      - name: Force Failue
        run: (exit 1)

